import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import cookies from '@utils/cookies'
import FriendHoc from '@utils/nextjs-friend'

const Home: NextPage = () => {

  /**
   * logout functionality.
   */
  const logout: any = () => {
    cookies.set('auth',false,{ path: '/' })
    cookies.set('token','',{ path: '/' })
    cookies.remove('auth',{ path: '/' })
    cookies.remove('token', { path: '/' })
    window.location.replace('/login')
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">NEXTJS friend</a>
        </h1>

        <p className={styles.description}>
          Nextjs boilerplate
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <p>Home</p>
          </a>
          <a
            href="#"
            className={styles.card}
            onClick={() => logout()}
          >
            <p>logout</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='#'
        >
          code4mk.org
        </a>
      </footer>
    </div>
  )
}

export default FriendHoc(Home, {
  middleware: ['auth']
})
